### ISSUE TITLE
Vue-class-compnent is used instead of Nuxt-class-component

### ISSUE THREAD

**Issue by AndrewBogdanovTSS** [DavidBernal/nuxt-property-decorator#1]
Please, fix this error. nuxt-class-component should be used as a dependency in the project. Right now you are using vue-class-component which leads to TS errors when using Nuxt Component's specific properties such as `fetch` or `middleware`. You need to change 
`import Component, { createDecorator } from 'vue-class-component';`
to
`import Component, { createDecorator } from 'nuxt-class-component';`
in [nuxt-property-decorator.ts](https://github.com/DavidBernal/nuxt-property-decorator/blob/master/src/nuxt-property-decorator.ts)

**Comment by DavidBernal** [comment]
I don't have time currently. Can you create a PR with the changes?
If not, this must wait.

**Comment by AndrewBogdanovTSS** [comment]
The problem is nuxt-class-component is currently also broken. It has an issue I logged here [nuxt-class-component/issues/11](https://github.com/nuxt-community/nuxt-class-component/issues/11)
The second problem is that `nuxt-class-component` doesn't expose `createDecorator` function that you rely upon. 
Until it will be fixed tests in your repo won't be green. So I'm blocked on this issue currently

**Comment by DavidBernal** [comment]
Exactly, nuxt-class-component doesn't have the createDecorator that I use for attach the nuxt hooks.

**Comment by DavidBernal** [comment]
FYI, this lib is used in my [typescript-express-decorators-template.](https://github.com/DavidBernal/typescript-express-decorators-template/blob/master/template/pages/_id.vue).
Without this library, you can't use asyncData in class component.

**Comment by hartmut-co-uk** [comment]
I think `nuxt-class-component` is stable now, should the issue be re-opened?

**Comment by AndrewBogdanovTSS** [comment]
@hartmut-co-uk I think it would be reasonable to consider such option again, but it's all up to @DavidBernal  to decide
