### ISSUE TITLE
Why this module doesn't reuse vue-property-decorator?

### ISSUE THREAD

**Issue by AndrewBogdanovTSS** [DavidBernal/nuxt-property-decorator#2]
@DavidBernal I looked closely into your code and I completely don't understand why do you rewrite all decorators from scratch? Wouldn't it be easier to import vue-property-decorator as a project dependency and inherit your decorator from it? Basically, in the current form, your lib has no difference from vue-property-decorator, you don't even use nuxt-class-component so what's the point of using your lib in favor of vue-property-decorator?

**Comment by DavidBernal** [comment]
Because vue-property-decorator is outdated and npm module doesn't have some methods. If you have a dependency with a deprecated module you are fucked.
