### ISSUE TITLE
[Bug] Component entry point does not exist

### ISSUE THREAD

**Issue by AndrewBogdanovTSS** [DavidBernal/nuxt-property-decorator#5]
Hi. In a package.json file **lib/nuxt-property-decorator.umd** is referenced as the main entry point but there is no such file in the repo. When nuxt-property-decorator is used as a dependency it brakes build process with an error:

ERROR Failed to compile with 2 errors12:32:38
This dependency was not found:

nuxt-property-decorator in ./node_modules/ts-loader?{"appendTsSuffixTo":[{}]}!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./components/Card.vue, ./node_modules/ts-loader?{"appendTsSuffixTo":[{}]}!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./pages/index.vue
To install it, you can run: npm install --save nuxt-property-decorator

https://github.com/nuxt-community/typescript-template/issues/44

**Comment by nysos3** [comment]
@AndrewBogdanovTSS I pushed a fix via pull request, hopefully @DavidBernal will merge & publish to npm

**Comment by DavidBernal** [comment]
Fixed and npm module updated
